### PR TITLE
[WIP] Subject

### PR DESCRIPTION
**Pull request by mobily**
This PR adds the `Subject` implementation. #5 

What needs to be done? **Tests.** I hope I will add some tests as soon as possible.

### CODE REVIEW

**Comment by WhoAteDaCake** [comment]
Is there any way we could get this merged ? this is quite a useful feature

**Comment by mobily** [comment]
@WhoAteDaCake I want to add some tests (I didn't have much free time recently due to other responsibilities). Hopefully, I will finish this over the weekend 😉

**Comment by kitten** [comment]
@mobily That'd be awesome :+1: Let me know if you'd want me to take over.

**Comment by kitten** [comment]
@mobily Hiya, I've incorporated your changes just now, since I've picked up work on Wonka again. The subject type itself has been moved though. Regarding the implementation, I've rewritten it to use `Rebel.Array` which I've made to compile most of Wonka to plain Array operations, instead of relying on Belt for the JS output. This shouldn't affect its implementation much and is just because Wonka is now kept compatible with TypeScript with a complete set of typings :sparkles:

Apart from that tests are still TBD 😆

**Pull request closed without merging**
